-- MySQL Script generated by MySQL Workbench
-- Fri Jun 15 20:28:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdPark
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdPark
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdPark` DEFAULT CHARACTER SET utf8 ;
USE `bdPark` ;

-- -----------------------------------------------------
-- Table `bdPark`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdPark`.`servico` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `id_servico` INT NOT NULL,
  `nome_servico` VARCHAR(45) NULL,
  `acesso_servico` INT NULL,
  `tolerancia` INT NULL,
  `unidadeDeMedida` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdPark`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdPark`.`ticket` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `id_ticket` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `entrada` DATE NULL,
  `saida` DATE NULL,
  `valor` FLOAT NULL,
  `id_servico` INT NOT NULL,
  `id_caixa` INT NULL,
  PRIMARY KEY (`ID`, `id_servico`),
  INDEX `id_servico_idx` (`id_servico` ASC),
  CONSTRAINT `id_servico`
    FOREIGN KEY (`id_servico`)
    REFERENCES `bdPark`.`servico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdPark`.`TabelaPreco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdPark`.`TabelaPreco` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `id_tbpreco` INT NOT NULL,
  `tempo` DOUBLE NULL,
  `moeda` FLOAT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
