/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.park.screen;

/**
 *
 * @author Programador
 */
public class AreaLogo extends javax.swing.JPanel {

    /**
     * Creates new form AreaLogo
     */
    public AreaLogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 72)); // NOI18N
        jLabel2.setText("Tire S");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 230, 60));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Soft");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 110, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Programador\\Desktop\\icopasta\\faixas-de-pneus-sujos-desaparecendo-no-horizonte_1017-8084.jpg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 324, 355));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
