/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.park.screen;

import br.com.park.client.Cliente;
import br.com.park.client.Telefone;
import br.com.park.dtbase.ServicoDAO;
import br.com.park.dtbase.bdBack;
import br.com.park.job.Servicos;
import br.com.park.job.Ticket;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Anderson
 */
public class clientCads extends javax.swing.JPanel {

    private bdBack banco = new bdBack();
    private ServicoDAO bancoS = new ServicoDAO();

    /**
     * Creates new form clientCads
     */
    public clientCads() {
        initComponents();
        populaServico();
        hidePanel();
    }

    public void hidePanel() {
        pn_grupo.setVisible(false);
        pn_cliente.setVisible(false);
        ch_operador.add("");
        ch_operador.add("Operador");
        pn_login.setVisible(false);
    }

    public void btnHabilita() {
        if (!tf_clienteNome.getText().equalsIgnoreCase("")
                || !tf_clienteCPF.getText().equalsIgnoreCase("")) {
            btn_Salvar.setEnabled(false);
        } else {
            btn_Salvar.setEnabled(true);
        }
    }

    public void pn() {
        if (ch_operador.getSelectedItem().equals("Operador")) {
            pn_login.setVisible(true);
        }
        if (ch_operador.getSelectedItem().equals("")) {
            pn_login.setVisible(false);
        }
    }

    public int qualServico(String nomeServ) {
        int tempoTolerancia = 0;
        for (Servicos servico : bancoS.getBdServico()) {
            if (nomeServ.equalsIgnoreCase(servico.getNome())) {
                tempoTolerancia = servico.getTolerancia();
            }
        }
        return tempoTolerancia;
    }

    public final void populaServico() {
        cb_serv.removeAllItems();
        if (bancoS.getBdServico().isEmpty()) {
            cb_serv.addItem("Não possui");
        } else {
            for (Servicos servico : bancoS.getBdServico()) {
                cb_serv.addItem(servico.getNome());
            }
        }
    }

    public void switchRd(JRadioButton j, JRadioButton j1) {
        if (j.isSelected()) {
            j1.setSelected(false);
        }
    }

    public void limpaTela() {
        tf_clienteCPF.setText("");
        tf_clienteEmail.setText("");
        tf_clienteNome.setText("");
        tf_clienteNome.setText("");
    }

    /**
     * public void popTab() {
     *
     * ArrayList dados = new ArrayList(); String[] colunas = new String[]{"ID",
     * "Nome", "CPF", "Telefone", "E-mail"}; try { for (clienteMensalista
     * cliente : banco.getBdCliente()) { int id = cliente.getId(); String nome =
     * cliente.getNome(); String cpf = cliente.getCpf(); String telefone =
     * cliente.getTelefone(); String email = cliente.getEmail(); dados.add(new
     * Object[]{id, nome, cpf, telefone, email}); } } catch (Exception e) {
     * JOptionPane.showMessageDialog(null, "Erro Ao preencher" + e); }
     *
     * MinhaTabela Mtable = new MinhaTabela(dados, colunas);
     * tb_cadCliente.setModel(Mtable);
     * tb_cadCliente.getColumnModel().getColumn(0).setPreferredWidth(20);
     * tb_cadCliente.getColumnModel().getColumn(0).setResizable(false);
     * tb_cadCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
     * tb_cadCliente.getColumnModel().getColumn(1).setResizable(false);
     * tb_cadCliente.getColumnModel().getColumn(2).setPreferredWidth(90);
     * tb_cadCliente.getColumnModel().getColumn(2).setResizable(false);
     * tb_cadCliente.getColumnModel().getColumn(3).setPreferredWidth(90);
     * tb_cadCliente.getColumnModel().getColumn(3).setResizable(false);
     * tb_cadCliente.getColumnModel().getColumn(4).setPreferredWidth(108);
     * tb_cadCliente.getColumnModel().getColumn(4).setResizable(false);
     *
     * tb_cadCliente.getTableHeader().setReorderingAllowed(false);
     * tb_cadCliente.setAutoResizeMode(tb_cadCliente.AUTO_RESIZE_OFF);
     * tb_cadCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     * tb_cadCliente.setAlignmentY(RIGHT_ALIGNMENT); }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_cad = new javax.swing.JPanel();
        tf_clienteEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_clienteTelefone = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_clienteNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_clienteCPF = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rd_cliente = new javax.swing.JRadioButton();
        rd_funcionario = new javax.swing.JRadioButton();
        pn_grupo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ch_operador = new java.awt.Choice();
        pn_login = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btn_Salvar = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pn_cliente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_serv = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_cad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Usuário"));

        jLabel5.setText("E-mail:");

        try {
            tf_clienteTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_clienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_clienteTelefoneActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone:");

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rd_cliente.setText("Cliente ");
        rd_cliente.setRequestFocusEnabled(false);
        rd_cliente.setRolloverEnabled(false);
        rd_cliente.setVerifyInputWhenFocusTarget(false);
        rd_cliente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rd_clienteStateChanged(evt);
            }
        });

        rd_funcionario.setText("Funcionário");
        rd_funcionario.setRequestFocusEnabled(false);
        rd_funcionario.setRolloverEnabled(false);
        rd_funcionario.setVerifyInputWhenFocusTarget(false);
        rd_funcionario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rd_funcionarioStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rd_cliente)
                .addGap(18, 18, 18)
                .addComponent(rd_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_cliente)
                    .addComponent(rd_funcionario)))
        );

        javax.swing.GroupLayout pn_cadLayout = new javax.swing.GroupLayout(pn_cad);
        pn_cad.setLayout(pn_cadLayout);
        pn_cadLayout.setHorizontalGroup(
            pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadLayout.createSequentialGroup()
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pn_cadLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_clienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_clienteEmail))
                        .addGroup(pn_cadLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_clienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_clienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(pn_cadLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_cadLayout.setVerticalGroup(
            pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_clienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_clienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_clienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_clienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        add(pn_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 520, 140));

        jLabel6.setText("Grupo:");

        ch_operador.setName(""); // NOI18N
        ch_operador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch_operadorItemStateChanged(evt);
            }
        });
        ch_operador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ch_operadorFocusGained(evt);
            }
        });

        pn_login.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pn_loginPropertyChange(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jLabel3.setText("Login");

        jLabel9.setText("Senha:");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout pn_loginLayout = new javax.swing.GroupLayout(pn_login);
        pn_login.setLayout(pn_loginLayout);
        pn_loginLayout.setHorizontalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pn_loginLayout.setVerticalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout pn_grupoLayout = new javax.swing.GroupLayout(pn_grupo);
        pn_grupo.setLayout(pn_grupoLayout);
        pn_grupoLayout.setHorizontalGroup(
            pn_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_grupoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch_operador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_grupoLayout.setVerticalGroup(
            pn_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_grupoLayout.createSequentialGroup()
                .addGroup(pn_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_grupoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(pn_grupoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ch_operador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pn_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 520, 40));

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_remove.setText("Remover");

        jButton1.setText("Buscar");
        jButton1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_remove)
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_remove)
                        .addComponent(btn_Salvar))
                    .addComponent(jButton1)))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jLabel7.setText("Código Passe:");

        jLabel8.setText("Serviço: ");

        cb_serv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pn_clienteLayout = new javax.swing.GroupLayout(pn_cliente);
        pn_cliente.setLayout(pn_clienteLayout);
        pn_clienteLayout.setHorizontalGroup(
            pn_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_clienteLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pn_clienteLayout.setVerticalGroup(
            pn_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_clienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(11, 11, 11))
            .addGroup(pn_clienteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pn_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        add(pn_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 520, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed

        Telefone tel = new Telefone();
        Ticket passe = new Ticket();
        try {
            passe.setCodigo(Integer.parseInt(tf_codigo.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(tf_codigo, "Somente numeros no campo Código", "FORMATO CÓDIGO ERROR ", JOptionPane.ERROR_MESSAGE);

        }
        passe.setaHoraAtual();
        int tt = qualServico(cb_serv.getSelectedItem().toString());
        passe.setaHoraSaida(tt);
        Cliente cliente = new Cliente(tf_clienteTelefone.getText(), passe);
        cliente.setNome(tf_clienteNome.getText());
        cliente.setEmail(tf_clienteEmail.getText());
        cliente.setCpf(tf_clienteCPF.getText());
        banco.salvaCliente(cliente);
        btnHabilita();
        limpaTela();
        JOptionPane.showMessageDialog(pn_cad, "Salvo com sucesso!");
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void tf_clienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_clienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_clienteTelefoneActionPerformed

    private void rd_clienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rd_clienteStateChanged
        switchRd(rd_cliente, rd_funcionario);
        if (rd_cliente.isSelected()) {
            pn_cliente.setVisible(true);
        } else {
            pn_cliente.setVisible(false);
        }
    }//GEN-LAST:event_rd_clienteStateChanged

    private void rd_funcionarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rd_funcionarioStateChanged
        switchRd(rd_funcionario, rd_cliente);
        if (rd_funcionario.isSelected()) {
            ch_operador.select("");
            pn_grupo.setVisible(true);

        } else {
            pn_grupo.setVisible(false);
        }
        pn();
    }//GEN-LAST:event_rd_funcionarioStateChanged

    private void ch_operadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch_operadorItemStateChanged
        if (ch_operador.getSelectedItem().equals("Operador")) {
            pn_login.setVisible(true);
        }
    }//GEN-LAST:event_ch_operadorItemStateChanged

    private void ch_operadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ch_operadorFocusGained

    }//GEN-LAST:event_ch_operadorFocusGained

    private void pn_loginPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pn_loginPropertyChange
        if (ch_operador.getSelectedItem().equals("Operador")) {
            pn_login.setVisible(true);
        }
        if (ch_operador.getSelectedItem().equals("")) {
            pn_login.setVisible(false);
        }
    }//GEN-LAST:event_pn_loginPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_remove;
    private javax.swing.JComboBox<String> cb_serv;
    private java.awt.Choice ch_operador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pn_cad;
    private javax.swing.JPanel pn_cliente;
    private javax.swing.JPanel pn_grupo;
    private javax.swing.JPanel pn_login;
    private javax.swing.JRadioButton rd_cliente;
    private javax.swing.JRadioButton rd_funcionario;
    private javax.swing.JFormattedTextField tf_clienteCPF;
    private javax.swing.JTextField tf_clienteEmail;
    private javax.swing.JTextField tf_clienteNome;
    private javax.swing.JFormattedTextField tf_clienteTelefone;
    private javax.swing.JTextField tf_codigo;
    // End of variables declaration//GEN-END:variables
}
