/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.park.screen;

import br.com.park.dtbase.bdBack;
import br.com.park.logs.Logs;
import br.com.park.tools.MinhaTabela;
import static java.awt.Component.RIGHT_ALIGNMENT;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author info17
 */
public class RConsole extends javax.swing.JPanel {

    /**
     * Creates new form RLogs
     */
    public RConsole() {
        initComponents();
        populaLog();
    }
    public void populaLog(){
        
        tx_logWrite.setEditable(false);
        
        for (int i = 0; i < bdBack.getBdlog().size(); i++) {
            tx_logWrite.append(bdBack.getBdlog().get(i).toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tx_logWrite = new javax.swing.JTextArea();

        tx_logWrite.setColumns(20);
        tx_logWrite.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        tx_logWrite.setRows(5);
        jScrollPane3.setViewportView(tx_logWrite);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea tx_logWrite;
    // End of variables declaration//GEN-END:variables
}
