/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.park.screen;

import br.com.park.client.Telefone;
import br.com.park.client.clienteMensalista;
import br.com.park.client.clienteMensalista;
import br.com.park.dtbase.bdBack;
import br.com.park.job.Servicos;
import br.com.park.job.Ticket;
import br.com.park.tools.MinhaTabela;
import com.sun.javafx.animation.TickCalculation;
import static java.awt.Component.RIGHT_ALIGNMENT;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Anderson
 */
public class clientCads extends javax.swing.JPanel {

    private bdBack banco = new bdBack();

    /**
     * Creates new form clientCads
     */
    public clientCads() {
        initComponents();
        popTab();
        populaServico();
    }

    public void btnHabilita() {
        if (!tf_clienteNome.getText().equalsIgnoreCase("")
                || !tf_clienteCPF.getText().equalsIgnoreCase("")) {
            btn_Salvar.setEnabled(false);
        } else {
            btn_Salvar.setEnabled(true);
        }
    }

    public int qualServico(String nomeServ) {
        int tempoTolerancia = 0;
        for (Servicos servico : banco.getBdServico()) {
            if (nomeServ.equalsIgnoreCase(servico.getNome())) {
                tempoTolerancia = servico.getTolerancia();
            }
        }
        return tempoTolerancia;
    }

    public final void populaServico() {
        cb_serv.removeAll();
        if (banco.getBdServico().isEmpty()) {
            cb_serv.addItem("Não possui");
        } else {
            for (Servicos servico : banco.getBdServico()) {
                cb_serv.add(servico.getNome());
            }
        }
    }

    public void limpaTela() {
        tf_clienteCPF.setText("");
        tf_clienteEmail.setText("");
        tf_clienteNome.setText("");
        tf_clienteNome.setText("");
    }

    public void popTab() {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome", "CPF", "Telefone", "E-mail"};
        try {
            for (clienteMensalista cliente : banco.getBdCliente()) {
                int id = cliente.getId();
                String nome = cliente.getNome();
                String cpf = cliente.getCpf();
                String telefone = cliente.getTelefone().getTelefone();
                String email = cliente.getEmail();
                dados.add(new Object[]{id, nome, cpf, telefone, email});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro Ao preencher" + e);
        }

        MinhaTabela Mtable = new MinhaTabela(dados, colunas);
        tb_cadCliente.setModel(Mtable);
        tb_cadCliente.getColumnModel().getColumn(0).setPreferredWidth(20);
        tb_cadCliente.getColumnModel().getColumn(0).setResizable(false);
        tb_cadCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
        tb_cadCliente.getColumnModel().getColumn(1).setResizable(false);
        tb_cadCliente.getColumnModel().getColumn(2).setPreferredWidth(90);
        tb_cadCliente.getColumnModel().getColumn(2).setResizable(false);
        tb_cadCliente.getColumnModel().getColumn(3).setPreferredWidth(90);
        tb_cadCliente.getColumnModel().getColumn(3).setResizable(false);
        tb_cadCliente.getColumnModel().getColumn(4).setPreferredWidth(108);
        tb_cadCliente.getColumnModel().getColumn(4).setResizable(false);

        tb_cadCliente.getTableHeader().setReorderingAllowed(false);
        tb_cadCliente.setAutoResizeMode(tb_cadCliente.AUTO_RESIZE_OFF);
        tb_cadCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tb_cadCliente.setAlignmentY(RIGHT_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_cad = new javax.swing.JPanel();
        tf_clienteEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_clienteTelefone = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_clienteNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_clienteCPF = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btn_Salvar = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_serv = new java.awt.Choice();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        choice2 = new java.awt.Choice();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cadCliente = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_cad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Usuário"));

        jLabel5.setText("E-mail:");

        try {
            tf_clienteTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_clienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_clienteTelefoneActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefone:");

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Funcionário?");

        jCheckBox1.setText("Sim");

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_remove.setText("Remover");

        jButton1.setText("Buscar");
        jButton1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btn_remove)
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_remove)
                        .addComponent(btn_Salvar))
                    .addComponent(jButton1)))
        );

        jLabel7.setText("Código Passe:");

        jLabel8.setText("Serviço: ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Grupo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 30));

        javax.swing.GroupLayout pn_cadLayout = new javax.swing.GroupLayout(pn_cad);
        pn_cad.setLayout(pn_cadLayout);
        pn_cadLayout.setHorizontalGroup(
            pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadLayout.createSequentialGroup()
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_cadLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_cadLayout.createSequentialGroup()
                        .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pn_cadLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_clienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_clienteEmail))
                                .addGroup(pn_cadLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_clienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_clienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pn_cadLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel8)
                                    .addGap(1, 1, 1)
                                    .addComponent(cb_serv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pn_cadLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_cadLayout.setVerticalGroup(
            pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_clienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_clienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_clienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_clienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addComponent(cb_serv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox1))
                .addGap(7, 7, 7)
                .addGroup(pn_cadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(pn_cad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 520, 200));

        tb_cadCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_cadCliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 511, 172));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed

        Telefone tel = new Telefone();
        Ticket passe = new Ticket();
        try {
            passe.setCodigo(Integer.parseInt(tf_codigo.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(tf_codigo, "Somente numeros no campo Código", "FORMATO CÓDIGO ERROR ", JOptionPane.ERROR_MESSAGE);

        }
        passe.setaHoraAtual();
        int tt = qualServico(cb_serv.getSelectedItem().toString());
        passe.setaHoraSaida(tt);
        tel.setTelefone(tf_clienteTelefone.getText());
        clienteMensalista cliente = new clienteMensalista(tel, passe);
        cliente.setNome(tf_clienteNome.getText());
        cliente.setEmail(tf_clienteEmail.getText());
        cliente.setCpf(tf_clienteCPF.getText());
        banco.salvaCliente(cliente);
        btnHabilita();
        popTab();
        limpaTela();

        JOptionPane.showMessageDialog(pn_cad, "Salvo com sucesso!");
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void tf_clienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_clienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_clienteTelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_remove;
    private java.awt.Choice cb_serv;
    private java.awt.Choice choice2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_cad;
    private javax.swing.JTable tb_cadCliente;
    private javax.swing.JFormattedTextField tf_clienteCPF;
    private javax.swing.JTextField tf_clienteEmail;
    private javax.swing.JTextField tf_clienteNome;
    private javax.swing.JFormattedTextField tf_clienteTelefone;
    private javax.swing.JTextField tf_codigo;
    // End of variables declaration//GEN-END:variables
}
