/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.park.screen;

import br.com.park.dtbase.bdBack;
import br.com.park.job.Caixa;
import br.com.park.job.Estacionamento;
import br.com.park.job.Ticket;
import java.awt.Color;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anderson Martins
 * @data 24/03/2018
 *
 */
public class PrincipalPage extends JPanel {

    private bdBack banco = new bdBack();
    private Caixa cx = new Caixa();

    public PrincipalPage() {
        initComponents();
        initMethods();
    }

    public int qualServico(String nomeServ) {
        int tempoTolerancia = 0;
        for (int i = 0; i < banco.getBdServico().size(); i++) {
            if (nomeServ.equalsIgnoreCase(banco.getBdServico().get(i).getNome())) {
                tempoTolerancia = banco.getBdServico().get(i).getTolerancia();
            }
        }
        return tempoTolerancia;
    }

    public void limpaTela() {
        lb_dataEntrada.setText("");
        lb_HoraEntrada.setText("");
        lb_dataSaida.setText("");
        lb_horaSaida.setText("");
        lb_codigo.setText("");
        lb_tolerancia.setText("");
    }

    public void geraTicket() {
        DateFormat forma = DateFormat.getDateInstance();
        DateFormat forma1 = DateFormat.getTimeInstance();
        String servicoNome = cb_serv.getSelectedItem().toString();
        Caixa cx = new Caixa();
        Ticket passe = new Ticket();
        passe.setaHoraAtual();
        passe.setaHoraSaida(qualServico(servicoNome));
        lb_codigo.setText(String.valueOf(passe.gerarCodigo()));
        lb_dataEntrada.setText(String.valueOf(forma.format(passe.getEntrada())));
        lb_HoraEntrada.setText(String.valueOf(forma1.format(passe.getEntrada())));
        lb_dataSaida.setText(String.valueOf(forma.format(passe.getSaida())));
        lb_horaSaida.setText(String.valueOf(forma1.format(passe.getSaida())));
        lb_tolerancia.setText(String.valueOf(qualServico(servicoNome)));
        banco.salvaTicket(passe);
    }

    public void telaCobranca(Ticket passe) {
        DateFormat padrao = DateFormat.getDateInstance();
        DateFormat padrao2 = DateFormat.getDateTimeInstance();
        lb_codigoConsulta.setText(String.valueOf((int) passe.getCodigo()));
        lb_status.setText(passe.buscaStatus(lb_status));
        lb_validade.setText(String.valueOf(padrao2.format(passe.getSaida())));
        lb_cobrar.setText("R$ " + String.valueOf(passe.getValor()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initMethods() {//Usado para iniciar as coisas
        pn_novoCartao.setVisible(false);
        banco.popComboServ(cb_serv);
        banco.popCombConvenio(cb_convenio);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_novoTicket = new javax.swing.JToggleButton();
        pn_consulta = new javax.swing.JPanel();
        l2 = new java.awt.Label();
        cb_convenio = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_validade = new javax.swing.JLabel();
        lb_status = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_cobrar = new javax.swing.JLabel();
        btn_consultar = new java.awt.Button();
        l3 = new java.awt.Label();
        tx_cod = new java.awt.TextField();
        button1 = new java.awt.Button();
        lb_txCódigo = new javax.swing.JLabel();
        lb_codigoConsulta = new javax.swing.JLabel();
        pn_novoCartao = new java.awt.Panel();
        btn_Gerar = new java.awt.Button();
        l_c = new java.awt.Label();
        lb_codigo = new java.awt.Label();
        lb_tolerancia = new java.awt.Label();
        btn_clear = new java.awt.Button();
        l_t = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        l_hora = new java.awt.Label();
        lb_HoraEntrada = new java.awt.Label();
        l_data = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        l_e = new java.awt.Label();
        lb_dataEntrada = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        l_horaS = new java.awt.Label();
        l_dataS = new java.awt.Label();
        lb_dataSaida = new java.awt.Label();
        lb_horaSaida = new java.awt.Label();
        jPanel6 = new javax.swing.JPanel();
        l_s = new java.awt.Label();
        l1 = new java.awt.Label();
        cb_serv = new java.awt.Choice();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btn_novoTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/park/img/download_1.jpeg"))); // NOI18N
        btn_novoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoTicketActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_novoTicket);

        add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 774, 40));

        pn_consulta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        l2.setText("Desconto:");

        jLabel1.setText("Validade:");

        jLabel2.setText("Status:");

        jLabel5.setText("Valor:");

        lb_cobrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_consultar.setLabel("Consultar");
        btn_consultar.setName(""); // NOI18N
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        l3.setName("l3"); // NOI18N
        l3.setText("Codigo:");

        tx_cod.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tx_cod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tx_codFocusGained(evt);
            }
        });
        tx_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_codActionPerformed(evt);
            }
        });

        button1.setLabel("R$ PAGAR");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        lb_txCódigo.setText("Código:");

        javax.swing.GroupLayout pn_consultaLayout = new javax.swing.GroupLayout(pn_consulta);
        pn_consulta.setLayout(pn_consultaLayout);
        pn_consultaLayout.setHorizontalGroup(
            pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_consultaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_consultaLayout.createSequentialGroup()
                        .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_consultaLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_consultaLayout.createSequentialGroup()
                                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_convenio, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_consultaLayout.createSequentialGroup()
                                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(tx_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_consultaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_consultaLayout.createSequentialGroup()
                                .addComponent(lb_txCódigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_codigoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pn_consultaLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_validade, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_consultaLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pn_consultaLayout.createSequentialGroup()
                                            .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pn_consultaLayout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(lb_cobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))))
                        .addGap(45, 45, 45))))
        );
        pn_consultaLayout.setVerticalGroup(
            pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_consultaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_convenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_txCódigo)
                    .addComponent(lb_codigoConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_validade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lb_cobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        l2.getAccessibleContext().setAccessibleName("");
        l2.getAccessibleContext().setAccessibleDescription("");

        add(pn_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 41, 322, -1));

        pn_novoCartao.setBackground(new java.awt.Color(204, 204, 204));
        pn_novoCartao.setEnabled(false);
        pn_novoCartao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Gerar.setLabel("Gerar");
        btn_Gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GerarActionPerformed(evt);
            }
        });
        pn_novoCartao.add(btn_Gerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 77, -1));

        l_c.setText("Código:");
        pn_novoCartao.add(l_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, -1));

        lb_codigo.setAlignment(java.awt.Label.CENTER);
        lb_codigo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pn_novoCartao.add(lb_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, -1));
        pn_novoCartao.add(lb_tolerancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, -1));

        btn_clear.setLabel("Limpar");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        pn_novoCartao.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 75, -1));

        l_t.setText("Tolerância:");
        pn_novoCartao.add(l_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        l_hora.setText("Hora:");

        lb_HoraEntrada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        l_data.setText("Data:");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_e.setText("Entrada");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(l_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lb_dataEntrada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_HoraEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_dataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_HoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(l_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pn_novoCartao.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, -1));

        l_horaS.setText("Hora:");

        l_dataS.setText("Data:");

        lb_dataSaida.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        lb_horaSaida.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        l_s.setText("Saída");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(l_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l_horaS, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_dataS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_horaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_dataSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l_horaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_dataS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lb_horaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_dataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_novoCartao.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, -1));

        l1.setText("Serviço:");
        pn_novoCartao.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 50, -1));
        pn_novoCartao.add(cb_serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 130, -1));

        add(pn_novoCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 370, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GerarActionPerformed
        if (cb_serv.getSelectedItem() == "Não possui") {
            JOptionPane.showMessageDialog(btn_Gerar, "Verificar Serviço");
        } else {
            geraTicket();
        }
    }//GEN-LAST:event_btn_GerarActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        limpaTela();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        String txt = lb_codigo.getText();
        if (btn_consultar.getLabel().equals("Consultar")) {
            try {
                double tega = Double.valueOf(tx_cod.getText());
                tx_cod.setText("");
                telaCobranca(banco.consultaTicket(tega));
                //criar uma exceção com try catch para caso a pessoa coloque algo que não seja numero
                btn_consultar.setLabel("Desistir");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(pn_consulta, "Somente numeros no campo consulta", "ERROR CONSULTA", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            lb_codigoConsulta.setText("");
            lb_validade.setText("");
            lb_cobrar.setText("");
            lb_status.setText("");
            btn_consultar.setLabel("Consultar");

        }

    }//GEN-LAST:event_btn_consultarActionPerformed

    private void tx_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_codActionPerformed

    private void btn_novoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoTicketActionPerformed
        if (!pn_novoCartao.isVisible()) {
            pn_novoCartao.setBounds(341, 32, 400, 250);
            pn_novoCartao.setVisible(true);
            pn_novoCartao.setEnabled(true);
        } else {
            pn_novoCartao.setVisible(false);
        }
    }//GEN-LAST:event_btn_novoTicketActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void tx_codFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tx_codFocusGained
        cx.attReceita();
    }//GEN-LAST:event_tx_codFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_Gerar;
    private java.awt.Button btn_clear;
    private java.awt.Button btn_consultar;
    private javax.swing.JToggleButton btn_novoTicket;
    private java.awt.Button button1;
    private java.awt.Choice cb_convenio;
    private java.awt.Choice cb_serv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Label l1;
    private java.awt.Label l2;
    private java.awt.Label l3;
    private java.awt.Label l_c;
    private java.awt.Label l_data;
    private java.awt.Label l_dataS;
    private java.awt.Label l_e;
    private java.awt.Label l_hora;
    private java.awt.Label l_horaS;
    private java.awt.Label l_s;
    private java.awt.Label l_t;
    private java.awt.Label lb_HoraEntrada;
    private javax.swing.JLabel lb_cobrar;
    private java.awt.Label lb_codigo;
    private javax.swing.JLabel lb_codigoConsulta;
    private java.awt.Label lb_dataEntrada;
    private java.awt.Label lb_dataSaida;
    private java.awt.Label lb_horaSaida;
    private javax.swing.JLabel lb_status;
    private java.awt.Label lb_tolerancia;
    private javax.swing.JLabel lb_txCódigo;
    private javax.swing.JLabel lb_validade;
    private javax.swing.JPanel pn_consulta;
    private java.awt.Panel pn_novoCartao;
    private java.awt.TextField tx_cod;
    // End of variables declaration//GEN-END:variables
}
