/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.park.screen;

import br.com.park.dtbase.bdBack;
import br.com.park.tools.MinhaTabela;
import java.awt.print.PrinterException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Anderson
 */
public class RTrafego extends javax.swing.JPanel {
    bdBack banco = new bdBack();
    /**
     * Creates new form RTrafego
     */
    public RTrafego() {
        initComponents();
        popTabela();
        comboAtt();
    }
    public void comboAtt(){
        banco.popComboServ(cb_serv);
        cb_serv.addItem("");
        cb_serv.select(banco.getBdServico().size());
        
    }
    public void popTabela(){
        DateFormat forma = DateFormat.getDateInstance();
        DateFormat forma1 = DateFormat.getTimeInstance();
        bdBack banco = new bdBack();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Código","Data Entrada",
            "Hora Entrada","Data Saida","Hora Saida",
            "Serviço","Tempo","Unidade"};
        try {
            for (int x = 0; x < banco.getBdTicket().size(); x++) {
            int id = banco.getBdTicket().get(x).getId();
            int codigo = (int)banco.getBdTicket().get(x).getCodigo();
            Date entrada = banco.getBdTicket().get(x).getEntrada();
            Date saida = banco.getBdTicket().get(x).getSaida();
           
            String dataIn = forma.format(entrada);
            String horaIn = forma1.format(entrada);
            String dataOut = forma.format(saida);
            String horaOut = forma1.format(saida);
            
            dados.add(new Object[]{id,codigo,dataIn,horaIn,dataOut,horaOut,"","",""});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro Ao preencher"+e);
        }
       
        MinhaTabela Mtable = new MinhaTabela(dados,colunas);
        tb_regCod.setModel(Mtable);
        tb_regCod.getColumnModel().getColumn(0).setPreferredWidth(30);
        tb_regCod.getColumnModel().getColumn(0).setResizable(false);
        tb_regCod.getColumnModel().getColumn(1).setPreferredWidth(110);
        tb_regCod.getColumnModel().getColumn(1).setResizable(false);
        tb_regCod.getColumnModel().getColumn(2).setPreferredWidth(90);
        tb_regCod.getColumnModel().getColumn(2).setResizable(false);
        tb_regCod.getColumnModel().getColumn(3).setPreferredWidth(90);
        tb_regCod.getColumnModel().getColumn(3).setResizable(false);
        tb_regCod.getColumnModel().getColumn(4).setPreferredWidth(80);
        tb_regCod.getColumnModel().getColumn(4).setResizable(false);
        tb_regCod.getColumnModel().getColumn(5).setPreferredWidth(80);
        tb_regCod.getColumnModel().getColumn(5).setResizable(false);
        tb_regCod.getColumnModel().getColumn(6).setPreferredWidth(80);
        tb_regCod.getColumnModel().getColumn(6).setResizable(false);
        tb_regCod.getColumnModel().getColumn(7).setPreferredWidth(77);
        tb_regCod.getColumnModel().getColumn(7).setResizable(false);
        tb_regCod.getColumnModel().getColumn(8).setPreferredWidth(80);
        tb_regCod.getColumnModel().getColumn(8).setResizable(false);
        
        tb_regCod.getTableHeader().setReorderingAllowed(false);
        tb_regCod.setAutoResizeMode(tb_regCod.AUTO_RESIZE_OFF);
        tb_regCod.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tb_regCod.setAlignmentY(RIGHT_ALIGNMENT);
    }
    public void pesquisa(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_regCod = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_imprimir = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        cb_serv = new java.awt.Choice();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_regCod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_regCod);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 720, 290));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Movimento");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_imprimir.setLabel("Imprimir");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 90, -1));

        jLabel1.setText("Serviço:");

        jLabel2.setText("Data");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/park/img/ICONE-LUPA.jpg"))); // NOI18N
        jButton1.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_serv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 460, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        try {
            tb_regCod.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(btn_imprimir, "ERRO ao imprimir");
        }
    }//GEN-LAST:event_btn_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_imprimir;
    private java.awt.Choice cb_serv;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_regCod;
    // End of variables declaration//GEN-END:variables
}
